import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export const US_STATES = [
  { id: 1, name: "States", value: "", shortName: "" },
  { id: 2, name: "Alabama", value: "Alabama", shortName: "AL" },
  { id: 3, name: "Alaska", value: "Alaska", shortName: "AK" },
  { id: 4, name: "Arizona", value: "Arizona", shortName: "AZ" },
  { id: 5, name: "Arkansas", value: "Arkansas", shortName: "AR" },
  { id: 6, name: "California", value: "California", shortName: "CA" },
  { id: 7, name: "Colorado", value: "Colorado", shortName: "CO" },
  { id: 8, name: "Connecticut", value: "Connecticut", shortName: "CT" },
  { id: 9, name: "Delaware", value: "Delaware", shortName: "DE" },
  { id: 10, name: "Florida", value: "Florida", shortName: "FL" },
  { id: 11, name: "Georgia", value: "Georgia", shortName: "GA" },
  { id: 12, name: "Hawaii", value: "Hawaii", shortName: "HI" },
  { id: 13, name: "Idaho", value: "Idaho", shortName: "ID" },
  { id: 14, name: "Illinois", value: "Illinois", shortName: "IL" },
  { id: 15, name: "Indiana", value: "Indiana", shortName: "IN" },
  { id: 16, name: "Iowa", value: "Iowa", shortName: "IA" },
  { id: 17, name: "Kansas", value: "Kansas", shortName: "KS" },
  { id: 18, name: "Kentucky", value: "Kentucky", shortName: "KY" },
  { id: 19, name: "Louisiana", value: "Louisiana", shortName: "LA" },
  { id: 20, name: "Maine", value: "Maine", shortName: "ME" },
  { id: 21, name: "Maryland", value: "Maryland", shortName: "MD" },
  { id: 22, name: "Massachusetts", value: "Massachusetts", shortName: "MA" },
  { id: 23, name: "Michigan", value: "Michigan", shortName: "MI" },
  { id: 24, name: "Minnesota", value: "Minnesota", shortName: "MN" },
  { id: 25, name: "Mississippi", value: "Mississippi", shortName: "MS" },
  { id: 26, name: "Missouri", value: "Missouri", shortName: "MO" },
  { id: 27, name: "Montana", value: "Montana", shortName: "MT" },
  { id: 28, name: "Nebraska", value: "Nebraska", shortName: "NE" },
  { id: 29, name: "Nevada", value: "Nevada", shortName: "NV" },
  { id: 30, name: "New Hampshire", value: "New Hampshire", shortName: "NH" },
  { id: 31, name: "New Jersey", value: "New Jersey", shortName: "NJ" },
  { id: 32, name: "New Mexico", value: "New Mexico", shortName: "NM" },
  { id: 33, name: "New York", value: "New York", shortName: "NY" },
  { id: 34, name: "North Carolina", value: "North Carolina", shortName: "NC" },
  { id: 35, name: "North Dakota", value: "North Dakota", shortName: "ND" },
  { id: 36, name: "Ohio", value: "Ohio", shortName: "OH" },
  { id: 37, name: "Oklahoma", value: "Oklahoma", shortName: "OK" },
  { id: 38, name: "Oregon", value: "Oregon", shortName: "OR" },
  { id: 39, name: "Pennsylvania", value: "Pennsylvania", shortName: "PA" },
  { id: 40, name: "Rhode Island", value: "Rhode Island", shortName: "RI" },
  { id: 41, name: "South Carolina", value: "South Carolina", shortName: "SC" },
  { id: 42, name: "South Dakota", value: "South Dakota", shortName: "SD" },
  { id: 43, name: "Tennessee", value: "Tennessee", shortName: "TN" },
  { id: 44, name: "Texas", value: "Texas", shortName: "TX" },
  { id: 45, name: "Utah", value: "Utah", shortName: "UT" },
  { id: 46, name: "Vermont", value: "Vermont", shortName: "VT" },
  { id: 47, name: "Virginia", value: "Virginia", shortName: "VA" },
  { id: 48, name: "Washington", value: "Washington", shortName: "WA" },
  { id: 49, name: "West Virginia", value: "West Virginia", shortName: "WV" },
  { id: 50, name: "Wisconsin", value: "Wisconsin", shortName: "WI" },
  { id: 51, name: "Wyoming", value: "Wyoming", shortName: "WY" },
] as const;
